name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: programa
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: leonardosartorello
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v2

    - name: Verify Docker Compose installation
      run: docker-compose --version

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: leonardosartorello/go_ci:${{github.ref_name}}
